# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SQL_search_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.wynik_table = QtWidgets.QTableWidget(self.centralwidget)
        self.wynik_table.setStyleSheet("gridline-color: rgb(0, 0, 0);\n" "")
        self.wynik_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wynik_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.wynik_table.setMidLineWidth(1)
        self.wynik_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.wynik_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.wynik_table.setAlternatingRowColors(True)
        self.wynik_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.wynik_table.setShowGrid(True)
        self.wynik_table.setWordWrap(True)
        self.wynik_table.setCornerButtonEnabled(True)
        self.wynik_table.setObjectName("wynik_table")
        self.wynik_table.setColumnCount(0)
        self.wynik_table.setRowCount(0)
        self.gridLayout.addWidget(self.wynik_table, 1, 0, 1, 1)
        self.wynik_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wynik_label.setFont(font)
        self.wynik_label.setObjectName("wynik_label")
        self.gridLayout.addWidget(self.wynik_label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wynik_table.setSortingEnabled(True)
        self.wynik_label.setText(_translate("MainWindow", "TextLabel"))
